In [34]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [40]:
drySpells = pd.read_csv ('drySpells.csv')
drySpells=drySpells.set_index(['Year', 'Month', 'State', 'City'])
frostDays=pd.read_csv('frostDays.csv')
frostDays=frostDays.set_index(['Year', 'Month', 'State', 'City'])
maxHighTemp=pd.read_csv('maxHighTemp.csv')
maxHighTemp=maxHighTemp.set_index(['Year', 'Month', 'State','City'])
minLowTemp=pd.read_csv('minLowTemp.csv')
minLowTemp=minLowTemp.set_index(['Year', 'Month', 'State','City'])
precipitation=pd.read_csv("precipitation.csv")
precipitation=precipitation.set_index(['Year', 'Month', 'State','City'])

In [41]:
df = pd.concat([drySpells, frostDays, maxHighTemp, minLowTemp, precipitation], axis=1)
df

                              AVG_Dry_Spell  AVG_Frost_Days  \
Year Month    State City
2006 January  MD    Adelphi        0.666667       23.333333
     February MD    Adelphi        0.523810       16.000000
     March    MD    Adelphi        0.619048       12.809524
     April    MD    Adelphi        0.428571        2.619048
     May      MD    Adelphi        0.380952        0.095238
...                                     ...             ...
2023 February MS    Ackerman       0.380952        9.571429
     March    MS    Ackerman       0.523810        3.523810
     April    MS    Ackerman       0.380952        0.238095
     May      MS    Ackerman       0.809524        0.000000
     June     MS    Ackerman       0.619048        0.000000

                              AVG_Max_High_Temp  AVG_Min_Low_Temp  \
Year Month    State City
2006 January  MD    Adelphi           58.380462          6.651906
     February MD    Adelphi           64.210977         12.375184
     March    MD    Adelphi           71.779725         18.881910
     April    MD    Adelphi           81.003826         29.565725
     May      MD    Adelphi           88.391318         39.327334
...                                         ...               ...
2023 February MS    Ackerman          72.482806         20.911195
     March    MS    Ackerman          78.052354         26.843988
     April    MS    Ackerman          85.743364         35.929822
     May      MS    Ackerman          92.352920         46.786917
     June     MS    Ackerman          98.425932         58.754547

                              AVG_Precip_Percentile
Year Month    State City
2006 January  MD    Adelphi                0.008978
     February MD    Adelphi                0.011565
     March    MD    Adelphi                0.010393
     April    MD    Adelphi                0.019990
     May      MD    Adelphi                0.044866
...                                             ...
2023 February MS    Ackerman               0.024384
     March    MS    Ackerman               0.041880
     April    MS    Ackerman               0.032186
     May      MS    Ackerman               0.021892
     June     MS    Ackerman               0.044507

[840 rows x 5 columns]

In [42]:
adelphi_df = df.reset_index(drop=False)
adelphi_df = adelphi_df.loc[adelphi_df['City']=='Adelphi']
adelphi_df['Date'] = adelphi_df['Year'].astype(str) + '-' + adelphi_df['Month'].astype(str)
adelphi_df = adelphi_df.drop(['Month', 'State', 'City', 'Year'], axis=1).set_index('Date')
adelphi_df.index = pd.to_datetime(adelphi_df.index)

ack_df = df.reset_index(drop=False)
ack_df = ack_df.loc[ack_df['City']=='Ackerman']
ack_df['Date'] = ack_df['Year'].astype(str) + '-' + ack_df['Month'].astype(str)
ack_df = ack_df.drop(['Month', 'State', 'City', 'Year'], axis=1).set_index('Date')
ack_df.index = pd.to_datetime(ack_df.index)

albany_df = df.reset_index(drop=False)
albany_df = albany_df.loc[albany_df['City']=='Albany']
albany_df['Date'] = albany_df['Year'].astype(str) + '-' + albany_df['Month'].astype(str)
albany_df = albany_df.drop(['Month', 'State', 'City', 'Year'], axis=1).set_index('Date')
albany_df.index = pd.to_datetime(albany_df.index)

alachua_df = df.reset_index(drop=False)
alachua_df = alachua_df.loc[alachua_df['City']=='Alachua']
alachua_df['Date'] = alachua_df['Year'].astype(str) + '-' + alachua_df['Month'].astype(str)
alachua_df = alachua_df.drop(['Month', 'State', 'City', 'Year'], axis=1).set_index('Date')
alachua_df.index = pd.to_datetime(alachua_df.index)


# Saving weather data for each city for further analysis
adelphi_df.to_csv('adelphi_df')
ack_df.to_csv('ack_df')
albany_df.to_csv('albany_df')
alachua_df.to_csv('alachua_df')