In [11]:
import requests
import json
import pandas as pd
auth = {"Authorization": "Token e3242fc4e9da547a8adda3abbcf328baa8e2ddd4"}
url = "https://app.climate.azavea.com/api/climate-data/344/RCP85/indicator/percentile_precipitation/?time_aggregation=monthly"
resp = requests.get(url, headers=auth)
resp_obj=resp.content

In [12]:
data=json.loads(resp_obj)
df=pd.DataFrame(data['data'])
adelphiDrySpells=df.transpose()
adelphiDrySpells.index.name='Year'
adelphiDrySpells=adelphiDrySpells.reset_index()
adelphiDrySpells[['Year', 'Month']] = adelphiDrySpells['Year'].str.split('-', expand=True)
adelphiDrySpells = adelphiDrySpells.reindex(columns=['Year','Month', 'avg'])
adelphiDrySpells[['Year', 'Month']] = adelphiDrySpells[['Year', 'Month']].astype(int)
adelphiDrySpells = adelphiDrySpells[(adelphiDrySpells['Year'] >= 2006) & (adelphiDrySpells['Year'] <= 2023)]
adelphiDrySpells = adelphiDrySpells.iloc[:-6,:]
adelphiDrySpells=adelphiDrySpells.set_index('Year')
month=adelphiDrySpells['Month']
monthList=[]
monthDict = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}
for num in month:
    month=monthDict[num]
    monthList.append(month)
adelphiDrySpells['Month']=monthList
adelphiDrySpells=adelphiDrySpells.rename(columns={'avg': 'Adelphi_MD'})
adelphiDrySpells=adelphiDrySpells.reset_index()
adelphiDrySpells=adelphiDrySpells.set_index(['Year', 'Month'])

In [13]:
auth1 = {"Authorization": "Token e3242fc4e9da547a8adda3abbcf328baa8e2ddd4"}
url1 = "https://app.climate.azavea.com/api/climate-data/1133/RCP85/indicator/percentile_precipitation/?time_aggregation=monthly"
resp1 = requests.get(url1, headers=auth1)
resp_obj1=resp1.content

In [14]:
data1=json.loads(resp_obj1)
df1=pd.DataFrame(data1['data'])
albanyDrySpells=df1.transpose()
albanyDrySpells.index.name='Year'
albanyDrySpells=albanyDrySpells.reset_index()
albanyDrySpells[['Year', 'Month']] = albanyDrySpells['Year'].str.split('-', expand=True)
albanyDrySpells = albanyDrySpells.reindex(columns=['Year','Month','avg'])
albanyDrySpells[['Year', 'Month']] = albanyDrySpells[['Year', 'Month']].astype(int)
albanyDrySpells = albanyDrySpells[(albanyDrySpells['Year'] >= 2006) & (albanyDrySpells['Year'] <= 2023)]
albanyDrySpells = albanyDrySpells.iloc[:-6,:]
albanyDrySpells=albanyDrySpells.set_index('Year')
month=albanyDrySpells['Month']
monthList=[]
monthDict = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}
for num in month:
    month=monthDict[num]
    monthList.append(month)
albanyDrySpells['Month']=monthList
albanyDrySpells=albanyDrySpells.rename(columns={'avg': 'Albany_CA'})
albanyDrySpells=albanyDrySpells.reset_index()
albanyDrySpells=albanyDrySpells.set_index(['Year', 'Month'])

In [15]:
auth2 = {"Authorization": "Token e3242fc4e9da547a8adda3abbcf328baa8e2ddd4"}
url2 = "https://app.climate.azavea.com/api/climate-data/1587/RCP85/indicator/percentile_precipitation/?time_aggregation=monthly"
resp2 = requests.get(url2, headers=auth2)
resp_obj2=resp2.content

In [16]:
data2=json.loads(resp_obj2)
df2=pd.DataFrame(data2['data'])
alachuaDrySpells=df2.transpose()
alachuaDrySpells.index.name='Year'
alachuaDrySpells=alachuaDrySpells.reset_index()
alachuaDrySpells[['Year', 'Month']] = alachuaDrySpells['Year'].str.split('-', expand=True)
alachuaDrySpells = alachuaDrySpells.reindex(columns=['Year','Month','avg'])
alachuaDrySpells[['Year', 'Month']] = alachuaDrySpells[['Year', 'Month']].astype(int)
alachuaDrySpells = alachuaDrySpells[(alachuaDrySpells['Year'] >= 2006) & (alachuaDrySpells['Year'] <= 2023)]
alachuaDrySpells = alachuaDrySpells.iloc[:-6,:]


alachuaDrySpells=alachuaDrySpells.set_index('Year')
month=alachuaDrySpells['Month']
monthList=[]
monthDict = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}
for num in month:
    month=monthDict[num]
    monthList.append(month)
alachuaDrySpells['Month']=monthList
alachuaDrySpells=alachuaDrySpells.rename(columns={'avg': 'Alachua_FL'})
alachuaDrySpells=alachuaDrySpells.reset_index()
alachuaDrySpells=alachuaDrySpells.set_index(['Year', 'Month'])

In [17]:
auth3 = {"Authorization": "Token e3242fc4e9da547a8adda3abbcf328baa8e2ddd4"}
url3 = "https://app.climate.azavea.com/api/climate-data/880/RCP85/indicator/percentile_precipitation/?time_aggregation=monthly"
resp3 = requests.get(url3, headers=auth3)
resp_obj3=resp3.content

In [21]:
data3=json.loads(resp_obj3)
df3=pd.DataFrame(data3['data'])
ackermanDrySpells=df3.transpose()
ackermanDrySpells.index.name='Year'
ackermanDrySpells=ackermanDrySpells.reset_index()
ackermanDrySpells[['Year', 'Month']] = ackermanDrySpells['Year'].str.split('-', expand=True)
ackermanDrySpells = ackermanDrySpells.reindex(columns=['Year','Month','avg'])
ackermanDrySpells[['Year', 'Month']] = ackermanDrySpells[['Year', 'Month']].astype(int)
ackermanDrySpells = ackermanDrySpells[(ackermanDrySpells['Year'] >= 2006) & (ackermanDrySpells['Year'] <= 2023)]
ackermanDrySpells = ackermanDrySpells.iloc[:-6,:]


ackermanDrySpells=ackermanDrySpells.set_index('Year')
month=ackermanDrySpells['Month']
monthList=[]
monthDict = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}
for num in month:
    month=monthDict[num]
    monthList.append(month)
ackermanDrySpells['Month']=monthList
ackermanDrySpells=ackermanDrySpells.rename(columns={'avg': 'Ackerman_MS'})
ackermanDrySpells=ackermanDrySpells.reset_index()
ackermanDrySpells=ackermanDrySpells.set_index(['Year', 'Month'])

In [22]:
cities=adelphiDrySpells
cities['Albany_CA']=albanyDrySpells
cities['Alachua_FL']=alachuaDrySpells
cities['Ackerman_MS']=ackermanDrySpells
cities=cities.reset_index()
cities

     Year     Month  Adelphi_MD  Albany_CA  Alachua_FL  Ackerman_MS
0    2006   January    0.008978   0.024288    0.025237     0.020218
1    2006  February    0.011565   0.054996    0.029095     0.035508
2    2006     March    0.010393   0.016353    0.008301     0.025910
3    2006     April    0.019990   0.008492    0.016765     0.050267
4    2006       May    0.044866   0.000690    0.040942     0.068791
..    ...       ...         ...        ...         ...          ...
205  2023  February    0.009181   0.030323    0.014978     0.024384
206  2023     March    0.018177   0.011267    0.015862     0.041880
207  2023     April    0.018859   0.004574    0.012846     0.032186
208  2023       May    0.041457   0.000118    0.023167     0.021892
209  2023      June    0.041154   0.000000    0.099446     0.044507

[210 rows x 6 columns]

In [23]:
melted = pd.melt(cities, id_vars=['Year', 'Month'], var_name='City_State')
melted[['City', 'State']] = melted['City_State'].str.split('_', expand=True)
melted.drop('City_State', axis=1, inplace=True)
melted = melted[['Year', 'Month', 'State', 'City', 'value']]
melted.rename(columns={'value': 'AVG_Precip_Percentile'}, inplace=True)
precipitation=melted.set_index(['Year', 'Month', 'State', 'City'])
display(precipitation)
precipitation.to_csv('precipitation.csv')

                              AVG_Precip_Percentile
Year Month    State City
2006 January  MD    Adelphi                0.008978
     February MD    Adelphi                0.011565
     March    MD    Adelphi                0.010393
     April    MD    Adelphi                0.019990
     May      MD    Adelphi                0.044866
...                                             ...
2023 February MS    Ackerman               0.024384
     March    MS    Ackerman               0.041880
     April    MS    Ackerman               0.032186
     May      MS    Ackerman               0.021892
     June     MS    Ackerman               0.044507

[840 rows x 1 columns]